### ISSUE TITLE
Feat/#13 Intro 섹션을 구현한다.

### ISSUE THREAD

**Issue by yuziwoo** [yuziwoo/portfolio#13]
### 📄 Describe

- 인트로 섹션을 구현한다.

### ✅ Tasks

- [x] 반응형에 맞게 인트로 섹션을 구현한다.
- [x] 새로운 디자인에 맞게 배경을 수정한다.
- [x] 4번째 배너를 구현한다.
- [x] MainLiner를 제거한다. 

### 🙋🏻 More

👍
