### ISSUE TITLE
[DOCS] 프론트엔드 manifest.json 설정

### ISSUE THREAD

**Issue by yuziwoo** [yuziwoo/portfolio#2]
### 📄 Describe

- 프론트엔드 manifest.json을 설정한다

### ✅ Tasks

- [x] manifest.json을 설정한다.
- [x] favicon, icon을 변경한다.
- [x] index.html을 설정한다.

### 🙋🏻 More

👍
