### ISSUE TITLE
Feat/#7 Section1을 구현한다.

### ISSUE THREAD

**Issue by yuziwoo** [yuziwoo/portfolio#7]
### 📄 Describe

- section1을 구현한다.

### ✅ Tasks

- [x] styled-components를 설치한다.
- [x] 좌측 텍스트를 오픈에니메이션과 함께 구현한다.
- [x] 첫번째 이미지 스와이퍼를 구현한다.
- [x] 두번째 이미지를 구현한다.

### 🙋🏻 More

👍
