### ISSUE TITLE
Feat/#9 Section2를 구현한다.

### ISSUE THREAD

**Issue by yuziwoo** [yuziwoo/portfolio#9]
### 📄 Describe

- Feat/# Section2를 구현한다.

### ✅ Tasks

- [ ] 반짝이는 구분선을 구현한다.
- [ ] 텍스트와 배경을 구현한다.
- [ ] 마우스에 반응하는 오브젝트를 구현한다.

### 🙋🏻 More

👍
